"""The documentation makes numeric claims. These check they are still true.

A repository whose entire argument is "claims should be checkable rather than trusted"
cannot ship a hero image asserting a test count that stopped being true four commits ago.
That already happened once: the README banner claimed 441 tests when there were 471.

So the numbers the docs assert about *this repo* are asserted back here. Numbers that come
from a full pipeline run are deliberately not pinned — they move when the generator or the
policy legitimately changes, and a test that fails on every honest improvement gets deleted
rather than obeyed. What is pinned is the class of claim that has no excuse for drifting.
"""
from __future__ import annotations

import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent


def read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8")


def test_the_advertised_test_count_is_real(request):
    """Every '<n> passed' claim in the docs must equal what this session actually collected."""
    actual = request.session.testscollected
    claims: list[tuple[str, int]] = []
    for name in ("README.md", "docs/demo.svg"):
        for found in re.findall(r"(\d{3,4}) passed", read(name)):
            claims.append((name, int(found)))
    assert claims, "no test-count claim found — did the docs stop advertising one?"
    wrong = [(n, c) for n, c in claims if c != actual]
    assert not wrong, (
        f"the docs claim {wrong} tests but this session collected {actual}. "
        f"Update the claim or stop making it."
    )


@pytest.mark.parametrize(
    "command",
    ["salvage demo", "salvage prove", "salvage sweep", "pytest tests/"],
)
def test_every_command_the_readme_advertises_exists(command):
    """A README that tells a reviewer to run something that does not exist is worse than silent."""
    assert command in read("README.md"), f"{command!r} is no longer advertised"
    if command.startswith("salvage "):
        from salvage import cli
        name = command.split()[1]
        assert hasattr(cli, name), f"README advertises `{command}` but cli has no {name}()"


def test_every_local_doc_link_in_the_readme_resolves():
    """A broken link in the front door is the cheapest possible own goal."""
    targets = re.findall(r"\]\((?!https?:)([^)#]+)", read("README.md"))
    missing = [t for t in targets if not (ROOT / t).exists()]
    assert not missing, f"README links to files that do not exist: {missing}"


def test_the_demo_svg_carries_no_stale_rupee_claim():
    """Every rupee figure in the hero image must also appear in RESULTS.md."""
    results = ROOT / "RESULTS.md"
    if not results.exists():
        pytest.skip("RESULTS.md is generated by `salvage demo`; not present in this checkout")
    body = results.read_text(encoding="utf-8")
    svg = read("docs/demo.svg")
    # Only the recovery/at-risk/gap figures, which come straight from a run.
    figures = set(re.findall(r"₹[\d,]+\.\d{2}", svg))
    orphaned = [f for f in figures if f not in body]
    assert not orphaned, (
        f"the hero image shows {orphaned} which RESULTS.md does not — regenerate one of them"
    )
